# Generated by Django 5.2.3 on 2025-06-12 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositorio',
            name='clone_url_ssh',
            field=models.CharField(blank=True, help_text='URL para clonar o repositório via SSH (formato SSH).', max_length=512, null=True),
        ),
    ]
